[package]
name = "yazi-claude-ide"
version = "0.2.1"
edition = "2024"
license = "MIT"
publish = false

[lib]
name = "yazi_claude_ide"
path = "src/lib.rs"

[[bin]]
name = "yazi-claude-ide"
path = "src/main.rs"

[dependencies]
futures-util = { version = "0.3.32", features = ["sink"] }
getrandom = "0.4.3"
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio ={ version = "1.53.1", features = ["rt", "macros", "net", "process", "signal", "time", "io-util", "sync"] }
tokio-tungstenite = "0.30.0"

[dev-dependencies]
tempfile = "3.27.0"
